# Generated by Django 2.0.9 on 2019-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contra', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('codigoPuntoControl', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nom_responsable', models.CharField(max_length=30)),
                ('lugar_asignado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoRuta',
            fields=[
                ('codigoPuntoRuta', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombrePunto', models.CharField(max_length=30)),
                ('cantidadUnidades', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('codigoReg', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('lugar', models.CharField(max_length=200)),
                ('cantidadPasajeros', models.IntegerField(blank=True, null=True)),
                ('cantidadDinero', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMotoriste', models.CharField(max_length=30)),
                ('numeroPlaca', models.CharField(max_length=7)),
                ('numeroAsientos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='administrador',
            name='unidadtransporte',
            field=models.ManyToManyField(blank=True, to='puntocontrolapp.UnidadTransporte'),
        ),
    ]
