# Generated by Django 2.0.9 on 2019-06-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntocontrolapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='unidadtransporte',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
