# Generated by Django 2.0.9 on 2019-06-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntocontrolapp', '0002_auto_20190613_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntocontrol',
            name='lugar_asignado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cantidadPasajeros',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='lugar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidadtransporte',
            name='numeroPlaca',
            field=models.CharField(max_length=8),
        ),
    ]
