# Generated by Django 2.0.9 on 2019-06-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntocontrolapp', '0003_auto_20190613_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntocontrol',
            name='puntocontrolregistro',
            field=models.ManyToManyField(blank=True, null=True, to='puntocontrolapp.UnidadTransporte'),
        ),
    ]
